### ISSUE TITLE
GFPGAN toggle on plugin GUI?

### ISSUE THREAD

**Issue by shockz0rz** [sddebz/stable-diffusion-krita-plugin#17]
I've found that leaving GFPGAN on in img2img when a face already looks fine sometimes leads to it being changed more than I'd like. I know it can already be switched in the krita_config.yaml file, but would it be possible to add a checkbox on the GUI to switch GFPGAN face fixing on or off quickly?

**Comment by sddebz** [comment]
Added toggle for GFPGAN in ui. Please set use_GPFGAN in krita_config.yaml to false, otherwise it will override ui.

Personally I just didn't find it very useful, img2img on face area or sd upscale usually works better. But that's probably because I prefer to generate not photorealistic pics, and GFPGAN doesn't work well with it.
